name: Deploy to Azure Functions

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'tds-rapidint'  # Replace with your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './azure-functions'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Install dependencies'
      shell: bash
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm ci --production

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: deploy-to-function
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Deployment Summary'
      run: |
        echo "✅ Deployment successful!"
        echo "Environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}"
        echo "Function App: ${{ env.AZURE_FUNCTIONAPP_NAME }}"
        echo "Branch: ${{ github.ref_name }}"
